### ISSUE TITLE
Deprecated version of the Android embedding

### ISSUE THREAD

**Issue by hekhy** [fweinaug/system_settings#12] opened 2021-09-13 13:18 UTC
```
The plugins `flutter_ringtone_player, system_settings` use a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
```

I receive this problem, when I launch my application, I can possibly fix it using the documentation mentioned in the same message, but I deduce that the problem is not only there since as you can see there is also another package that fails and all the other 11 packages that use my application do not have this problem, I suppose they should update the package to fix it.
I just wanted to comment on it, for the rest, excellent package.

**Comment by henry2man** [comment] 2021-09-14 10:47
It's a duplicate of #10 

@fweinaug Please close this one.

**Comment by hekhy** [comment] 2021-09-14 10:51
> Es un duplicado del [# 10](https://github.com/fweinaug/system_settings/issues/10)
> 
> @fweinaug Cierra este.

Disculpa, no lo vi!

**Closed** 2021-09-14 10:51 UTC
